AWSTemplateFormatVersion: "2010-09-09"

Resources:

  MyBucket:
    Type: AWS::S3::Bucket

  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "AccessToConfigInS3"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:GetObject"
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:s3:::"
                      - !Ref MyBucket
                      - "/config.yaml"
              - Effect: "Allow"
                Action: [ "s3:GetObject", "s3:PutObject" ]
                Resource: "arn:aws:s3:::*/lastRelease"
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:s3:::"
                      - !Ref MyBucket
                      - "/lastRelease"

  MyFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile:
          Fn::Join:
            - ""
            - - |
                  import boto3
                  import botocore
              - Fn::Join:
                  - ""
                  - - "BUCKET_NAME = '"
                    - !Ref MyBucket
                    - "' # replace with your bucket name\n"
              - |
                  KEY = 'config.yaml'

                  def my_handler(event, context):
                    print(event)
                    print(context)
                    s3 = boto3.resource('s3')

                    try:
                      s3.Bucket(BUCKET_NAME).download_file(KEY, 'config.yaml')
                    except botocore.exceptions.ClientError as e:
                      if e.response['Error']['Code'] == "404":
                        print("cannot find the configuration file 'config.yaml'.")
                      else:
                        raise

                    with open('config.yaml', 'r') as stream:
                      print(stream.read())

                    return { "message" : "all done" }
      Description: "Check the current NIXOS Release for a given version and update an S3 file"
      Handler: my_handler
      MemorySize: 256
      Role:
       Fn::GetAtt:
         - "MyRole"
         - "Arn"
      Runtime: "python3.6"
      Timeout: 60

Outputs:
  NixosReleaseBucket:
    Value: !Ref MyBucket
    Description: "Bucket that stores the last seen nixos release"
